# Generated by Django 6.0.7 on 2026-07-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
